version: "3"
services:
  frontend:                 
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend    
    container_name: app_frontend
    restart: always
    volumes:
      - ./frontend/:/app      
      - /app/node_modules
    stdin_open: true
    tty: true  
    networks:
      - app
              
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend  
    container_name: app_backend
    restart: always
    volumes:
      - ./backend/:/app      
      - /app/node_modules      
    environment:
      - NODE_PATH=src
      - PORT=3001
      - DB_HOST=postgres
      - DB=sample
      - REDIS_HOST=redis
      - REDIS_PORT=6379      
    networks:
      - app  
    depends_on:
      - postgres
      - redis 
    ports:
      - "3001:3001"

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx 
    ports:
      - "8080:80" 
    restart: always  
    networks:
      - app
    depends_on:
      - frontend
      - backend
    
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./database/postgres
    container_name: app_postgres
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "sample"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin" 
    networks:
      - app  
          
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app 
    volumes:
      - data:/data/redis   
    ports:
      - "6379:6379"
    restart: always    

networks: 
  app:
    driver: bridge

volumes:
  data:
    driver: local  